### PR TITLE
Load parsed body correctly

### PR DESCRIPTION
**Pull request by J0sueTM**
fixes https://github.com/moclojer/moclojer/issues/263

@avelino turns out it was the body that wasn't being parsed correctly.

Selmer, one of our dependencies, parses the body in a really specific way, and by not placing `safe` on evaluations, it will parse it correctly.

Now, we read these correctly, and try to parse back to json, in order to send the request correctly.

By putting `safe` on evaluations, I mean:

```yaml
    webhook:
      sleep-time: 0
      url: https://discord.com/api/webhooks/xxx/yyy/github
      method: POST
      body: "{{json-params|safe}}"
```

just using {{json-params}}, selmer would escape every quote or double quote as the urlsafe way, &quot;.

This imposes the enduser to place `safe` in order for things to work out. However, that wouldn't be straightfoward, right?. Do you think we should enforce `safe` ourselves when preprocessing the request body? This way the user wouldn't need to do it everytime.

## Summary by CodeRabbit

- **New Features**
	- Introduced a new helper function for parsing body strings from EDN format to JSON, enhancing error handling during parsing.
	- Simplified the `request-after-delay` function's signature for better flexibility and default handling.

- **Bug Fixes**
	- Improved logging within the `request-after-delay` function for better traceability of requests and errors.

- **Style**
	- Enhanced formatting and readability of multiple files, including alignment and whitespace adjustments in configuration and test files.

### CODE REVIEW

**Review by avelino — APPROVED** [review]
LGTM
@J0sueTM generate a new version for clojars

**Comment by J0sueTM** [comment]
@avelino any reasons to not wait for #262 to be merged before releasing a new version?

**Comment by avelino** [comment]
> @avelino any reasons to not wait for #262 to be merged before releasing a new version?

this change will be included in `v0.3.4`, so I proposed releasing `v0.3.3.1`
this way we can update the improvement for all users as soon as possible

**Comment by J0sueTM** [comment]
@avelino makes sense

**Pull request merged**
