### PR TITLE
Adds manual install script like babashka

### PR DESCRIPTION
**Pull request by rafaeldelboni**
I don´t know if you folks are open for PRs, but I just used your tool, which is super easy to use.

But I missed an easier way to install it on my dev machine, this PR aims to solve this for Linux and Mac users.

Regards.

### CODE REVIEW

**Review by avelino — APPROVED** [review]
LGTM

**Comment by avelino** [comment]
@rafaeldelboni thanks for helping to simplify the installation of moclojer, our mission is to be as familiar as possible for our users who don't know clojure (especially for those who just want to use moclojer and not contribute)

**Comment by rafaeldelboni** [comment]
Following your mission, maybe add 3 arguments to the main function would be nice:
`--help/-h`, `--config/-c` and `--mock/-m`
This would make moclojer even more like a cli tool, wdyt?

There are some tools to help this like [docopt.clj](https://github.com/nubank/docopt.clj)

**Comment by avelino** [comment]
I agree with both points, to keep the project organized (here on github) you can open two issues proposing these improvements?

**Comment by rafaeldelboni** [comment]
✅ 

https://github.com/moclojer/moclojer/issues/62
https://github.com/moclojer/moclojer/issues/63

**Pull request merged**
