### PR TITLE
Discussion log/level-min

### PR DESCRIPTION
**Pull request by matheusfrancisco**
@avelino changing how we log stuff.

this pr is not ready, still need to config https://stackoverflow.com/questions/14544991/how-to-configure-slf4j-simple 
min-level to remove org.jetty info log from pedestal.

fixed: #133

### CODE REVIEW

**Comment by avelino** [comment]
I like the solution, but the `[main]` logs is not needed, we need to remove it
```
[main] INFO org.eclipse.jetty.util.log - Logging initialized @4095ms to org.eclipse.jetty.util.log.Slf4jLog
2023-07-14T18:03:27.227Z Avelinos-Buser-MacBook-Pro.local ERROR [moclojer.io-utils:11] - :open-config :not-found file not found
2023-07-14T18:03:27.235Z Avelinos-Buser-MacBook-Pro.local INFO [moclojer.router:20] - :spec-mode :mode :moclojer
2023-07-14T18:03:27.239Z Avelinos-Buser-MacBook-Pro.local INFO [moclojer.server:40] - :moclojer-start -> moclojer :start-server :host 0.0.0.0 :port 8000 :url http://0.0.0.0:8000 :version dev :config-path /Users/avelino/.config/moclojer.yml :mocks-path nil
[main] INFO org.eclipse.jetty.server.Server - jetty-9.4.44.v20210927; built: 2021-09-27T23:02:44.612Z; git: 8da83308eeca865e495e53ef315a249d63ba9332; jvm 20.0.1
[main] INFO org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@397c53e7{/,null,AVAILABLE}
[main] INFO org.eclipse.jetty.server.AbstractConnector - Started ServerConnector@480842c9{HTTP/1.1, (http/1.1, h2c)}{0.0.0.0:8000}
[main] INFO org.eclipse.jetty.server.Server - Started @4638ms
```

**remove this:**
```log
[main] INFO org.eclipse.jetty.util.log - Logging initialized @4095ms to org.eclipse.jetty.util.log.Slf4jLog
...
[main] INFO org.eclipse.jetty.server.Server - jetty-9.4.44.v20210927; built: 2021-09-27T23:02:44.612Z; git: 8da83308eeca865e495e53ef315a249d63ba9332; jvm 20.0.1
[main] INFO org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@397c53e7{/,null,AVAILABLE}
[main] INFO org.eclipse.jetty.server.AbstractConnector - Started ServerConnector@480842c9{HTTP/1.1, (http/1.1, h2c)}{0.0.0.0:8000}
[main] INFO org.eclipse.jetty.server.Server - Started @4638ms
```

**Comment by souenzzo** [comment]
I created a branch where I switch from `slf4j-simple`, that prints direct to stdout, to `slf4j-jdk14`  that "forward" from slf4j into [JUL](https://docs.oracle.com/en/java/javase/20/docs/api/java.logging/java/util/logging/package-summary.html)


https://github.com/moclojer/moclojer/compare/main...souenzzo:moclojer:feat/filter-logs-jul

Things that I like in this PR:
- Small and simple change
- No extra deps
- Filter via clojure code

Things that I don't like in this PR:
- A custom formatter is required


Given this chart

concrete-bindings


I will try to:
- reuse the slf4j-simple formatter inside my solution
- try (again) to use filters with slf4j-simple

Logback seems to be "too big" for our use-case

If you like this current state, feel free to merge, use and customize it :)

**Review by avelino — APPROVED** [review]
LGTM

**Comment by souenzzo** [comment]
@avelino @matheusfrancisco  TIL:
We could add this property
`-Dorg.slf4j.simpleLogger.log.org.eclipse.jetty.server=error`

To the [build properties](https://github.com/moclojer/moclojer/blob/main/dev/moclojer/build.clj#L39)
instead of switch away from `slf4j-simple` and implement a custom logger


SimpleLogger configuration is more powerful than I expect 
https://www.slf4j.org/api/org/slf4j/simple/SimpleLogger.html

**Comment by matheusfrancisco** [comment]
sorry, didn't get it what is the main difference between what we have know to this approach?

**Comment by souenzzo** [comment]
get back to this comment:

- https://github.com/moclojer/moclojer/pull/135#issuecomment-1645720997

At that time, I was unable to solve the issue using this:

> try (again) to use filters with slf4j-simple

And now I discovered that it is possible to do.

**Pull request merged**
